# Generated by Django 5.1.6 on 2025-02-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado_publicacion',
            field=models.CharField(choices=[('draft', 'Borrador'), ('publish', 'Publicado')], default='draft', max_length=10),
        ),
    ]
