# Generated by Django 5.1.6 on 2025-02-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_estado_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado_publicacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_renta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_operacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('renta', 'Renta'), ('ambos', 'Venta y Renta')], default='venta', max_length=10),
        ),
    ]
