# Generated by Django 5.1.6 on 2025-02-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_variacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
