# Generated by Django 5.1.6 on 2025-02-21 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('inventario', '0006_remove_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacion',
            name='altura_tacon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.alturatacon'),
        ),
        migrations.AddField(
            model_name='variacion',
            name='metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.metal'),
        ),
        migrations.AddField(
            model_name='variacion',
            name='talla_calzado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.tallacalzado'),
        ),
    ]
