# Generated by Django 5.1.6 on 2025-02-22 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_tipooperacion'),
        ('inventario', '0007_variacion_altura_tacon_variacion_metal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacion',
            name='tipo_operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.tipooperacion'),
        ),
    ]
