# Generated by Django 5.1.6 on 2025-02-20 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tallaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tallaje', models.DateField(blank=True, null=True)),
                ('proximo_tallaje', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='tallajes/')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('firma_cliente', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallajes', to='ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='FotoTallaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='tallajes/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tallaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='tallajes.tallaje')),
            ],
        ),
    ]
